### ISSUE TITLE
Could not get comp for Wildboar spams log

### ISSUE THREAD

**Issue by Siriusoct** [gregorycu/AnimalGenetics#17]
For some reason whether or not there are wild boars on the map, "Could not get comp for:WildBoar" continuously spams the log with yellow errors. Here's the hugs log: [https://gist.github.com/HugsLibRecordKeeper/793b37ddfed2daed5ad183dcded3c7d7](url). This is one of the errors specifically, the only difference is the number after wildboar 
`Could not get comp for pawn: WildBoar47672
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
AnimalGenetics.Extensions:AnimalGenetics (Verse.Pawn)
AnimalGenetics.Extensions:GetGeneRecord (Verse.Pawn,RimWorld.StatDef)
AnimalGenetics.StatPart:GetFactor (RimWorld.StatRequest)
AnimalGenetics.StatPart:TransformValue (RimWorld.StatRequest,single&)
RimWorld.StatWorker:FinalizeValue (RimWorld.StatRequest,single&,bool)
(wrapper dynamic-method) RimWorld.StatWorker:RimWorld.StatWorker.GetValue_Patch0 (RimWorld.StatWorker,RimWorld.StatRequest,bool)
(wrapper dynamic-method) RimWorld.StatWorker:RimWorld.StatWorker.GetValue_Patch1 (RimWorld.StatWorker,Verse.Thing,bool)
(wrapper dynamic-method) RimWorld.StatExtension:RimWorld.StatExtension.GetStatValue_Patch2 (Verse.Thing,RimWorld.StatDef,bool)
PerfectPathing.ThisIsStupid:TicksPerMove_pawn (Verse.Pawn,bool)
(wrapper dynamic-method) Verse.AI.PathFinder:Verse.AI.PathFinder.FindPath_Patch1 (Verse.AI.PathFinder,Verse.IntVec3,Verse.LocalTargetInfo,Verse.TraverseParms,Verse.AI.PathEndMode,Verse.AI.PathFinderCostTuning)
Verse.AI.PathFinder:FindPath (Verse.IntVec3,Verse.LocalTargetInfo,Verse.Pawn,Verse.AI.PathEndMode,Verse.AI.PathFinderCostTuning)
Verse.AI.Pawn_PathFollower:GenerateNewPath ()
Verse.AI.Pawn_PathFollower:TrySetNewPath ()
Verse.AI.Pawn_PathFollower:TryEnterNextPathCell ()
(wrapper dynamic-method) Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.PatherTick_Patch3 (Verse.AI.Pawn_PathFollower)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
(wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch0 (Verse.TickList)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch0 (Verse.Root_Play)
`

**Comment by Siriusoct** [comment]
I'm not sure when it started but if I had to guess, I would say that adding the mod in an ongoing game caused the issue, as red errors popped up whenever I selected an animal that was from before I added the mod in. Though it might be a conflict with perfect pathfinding somehow? As it's mentioned in the errors, though I have no idea how they could conflict.

**Comment by gregorycu** [comment]
Please try the latest version.

**Comment by Siriusoct** [comment]
That fixed it! Thanks
