### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by ghost** [gregorycu/AnimalGenetics#8]
My team [yet from one person :( ] translated your fashion into Russian [Rimworld mods (Rus/Eng)]
[Russian for Animal Genetics.zip](https://github.com/gregorycu/AnimalGenetics/files/5213944/Russian.for.Animal.Genetics.zip)

**Comment by gregorycu** [comment]
95b1700cf0f6c5a98191e344123acb021194055a

Thank you GasterMin. If you provide your email address, we can make sure they work gets properly attributed to you.

**Comment by ghost** [comment]
Hello, I apologise for the long answer. My mail is 36402000@mail.ru.

**Comment by ghost** [comment]
I updated the translation for the new version of the mod. 
[Translation into Russian from September 23.zip](https://github.com/gregorycu/AnimalGenetics/files/5268360/Translation.into.Russian.from.September.23.zip)
